### ISSUE TITLE
Repeated CSS

### ISSUE THREAD

**Issue by chloetruax** [scoop444/company_website#2]
While it might seem minor for this, it can help your page scale with more elements when you create classes such as: 

``` css
.full-width{
width: 100%;
}

.full-height{
  height: 100%;
}
```
